### ISSUE TITLE
pairwise_corr: unclear doc

### ISSUE THREAD

**Issue by JoElfner** [raphaelvallat/pingouin#123]
Hi @raphaelvallat 

in my opinion, the doc of pairwise_corr is a bit unclear about the partial correlation. Imho it should be clarified, which correlation function (in this case `pg.corr`) is used, if `covar=None` and that partial corr. is only calculated, if `covar is not None`.

Furthermore, I'd like to see pairwise_corr to support the case that `columns=None` and that all columns are specified as covars, f.i. implicitly by setting `covar='all'` or explicitly by allowing to set `covar=data.columns`. This should calculate the `partial_corr` for all combinations of `x` and `y` while automatically excluding `x` and `y` from the covars.

If you think this could be useful, I'll start implementing it.

**Comment by raphaelvallat** [comment]
Hi @JoElfner,

I agree for the documentation, please feel free to submit a PR!

Just to make sure I understand your second point, the idea then would be to calculate the partial correlations between each pair of columns while controlling for all the other columns in the dataframe? Similar to what is done in [pingouin.pcorr](https://pingouin-stats.org/generated/pingouin.pcorr.html) function?

Thanks!

**Comment by JoElfner** [comment]
Hi @raphaelvallat ,

thanks, I'll give it a try!
 
Second point: Yep, that's exactly what I was thinking about. :)

**Comment by raphaelvallat** [comment]
I see! Well, that may require some changes to the code but hopefully nothing too hard. Do you want to give it a try too? 

I think I'd prefer `covar=df.columns` instead of `covar='all'`, just in case there's a column named "all" in the data which may be confusing. So, the "full patial correlation" would be applied only when `columns=None` and `covar` contains all the numeric columns of data. Does that make sense?

Thanks again!

**Comment by JoElfner** [comment]
Oh right, didn't think about columns named `'all'`. That's a good point...

I opened a PR with my proposed changes. There are still some points to discuss... :)
