### ISSUE TITLE
Two way repeated measures anova - the first row has a p value with null always

### ISSUE THREAD

**Issue by merjekrepo** [raphaelvallat/pingouin#129]
[rmAOV2way_long.xlsx](https://github.com/raphaelvallat/pingouin/files/5225880/rmAOV2way_long.xlsx)

I have a quick question:

When I apply post-hoc test for the two-way repeated measures anova using the attached file, I get the p value as nan of the first row. That happens with other datasets too.

```
file_name = "mydirectory\\rmAOV2way_long.xlsx"
df = pd.read_excel(file_name)
res = pg.pairwise_ttests(data=df, dv='rt', within=['iv1', 'iv2'], subject='Sub_id', padjust='sidak')
```

![two_way_pairwise_comparison](https://user-images.githubusercontent.com/12020185/93228163-d318c080-f73a-11ea-98fd-b11f00c42c9e.JPG)

Is that something normal? Or am I missing something?

**Comment by raphaelvallat** [comment]
Hi @merjekrepo, 

Can you please use Pingouin's Gitter chat for future questions: https://gitter.im/pingouin-stats/Lobby?

Here, the corrected p-value is NaN because you only have 2 levels and therefore one comparison in your "iv1" variable. So, it doesn't make sense to apply a multiple comparison procedure when you only have one test. You should therefore report the uncorrected p-value (p-unc).

The important thing to understand here is that the multiple comparison procedure is applied independently to each unique value in the "Contrast" column, e.g. iv1, then iv2 and then iv1 * iv2.

Hope this makes sense,
Raphael

**Comment by merjekrepo** [comment]
Sure @raphaelvallat , I use use that gitter platform, didn't know that exist :)

Thanks a lot for your answer. I get it now.
