### ISSUE TITLE
 handle missing values in Repeat measures one-way ANOVA

### ISSUE THREAD

**Issue by MOAMSA** [raphaelvallat/pingouin#158]
Hello, I have a table with the below columns ( for 20 participants in 6 different conditions).
`Participant Id, condition, response`
However, there are missing values in some conditions.
I think the One-way repeated measures might help to see the differences between these conditions. I tried to use `pg.rm_anova` and then `pg.pairwise_ttests`(Holm-corrected pairwise T-tests) and got this error:
`ValueError: Repeated measures data frame is not balanced. Subjects must have the same number of elements in all conditions, even when missing values are present.`

Is there any way to handle missing values? does the mixed-effects model help?
Thanks

**Comment by raphaelvallat** [comment]
Hi @MOAMSA,

Repeated measures ANOVA does not handle missing values. Note that this is true overall and not specific to Pingouin. The only solution is therefore to remove any participants with one or more missing values. Because they can handle missing values, linear mixed effect models are often far more useful than repeated measures ANOVA. However, they are not implemented in Pingouin. You will have to use JASP or R (lme4 package).

Thanks
Raphael

**Comment by raphaelvallat** [comment]
Closing this issue but please feel free to reopen.
