### ISSUE TITLE
2 way anova does not work with input column names containing -, # or space

### ISSUE THREAD

**Issue by Shuming13** [raphaelvallat/pingouin#169]
Hi, thank you so much for your amazing work!

I've been trying to run this line for 2 way ANOVA: 
`aov = data.anova(dv="size-average", between=["Media", "Line"], effsize="n2").round(3)`

And the error message I get is:
`PatsyError: Error evaluating factor: NameError: name 'size' is not defined`
`size-average ~ C(Media, Sum) * C(Line, Sum)`
`^^^^`

It works fine when I do one way ANOVA, but I start to have troubles when doing two way ANOVA. 
I don't think it's recognizing the column names with dash, space or other signs. 

Is there a way to deal with it without changing all the column names of the dataframe?

Thank you!

**Comment by raphaelvallat** [comment]
Hi @Shuming13,

It's because in the case of unbalanced two-way ANOVA, Pingouin relies on statsmodels and patsy, which are formula-based:

https://github.com/raphaelvallat/pingouin/blob/b369de9b8607e55061bc408e534e7d44443c744a/pingouin/parametric.py#L1139-L1147

Right now the workaround is to replace "-" by "_" in your variable name. In the future however, I think this can be fixed by doing (see https://patsy.readthedocs.io/en/latest/builtins-reference.html#patsy.builtins.Q)

```python
formula = "Q('" + dv + "') ~ "
```

I'll make this fix in the next stable release of Pingouin.

Thanks,
Raphael

**Comment by Shuming13** [comment]
Thank you so much!

**Comment by raphaelvallat** [comment]
Done in https://github.com/raphaelvallat/pingouin/commit/ab5662b92ab730d50c430cf44703c4c2b62402fc

**Comment by raphaelvallat** [comment]
This has been fixed in the new stable version of Pingouin ([v0.4.0](https://github.com/raphaelvallat/pingouin/releases/tag/v0.4.0)). Please make sure to upgrade with `pip install --upgrade pingouin`.

Thanks,
Closing the issue.
