### ISSUE TITLE
pairwise_nonparametric()

### ISSUE THREAD

**Issue by michalkahle** [raphaelvallat/pingouin#209]
Hi, I was looking for non-parametric pairwise tests and only found the parameter `parametric=False` of the `pairwise_ttests()` after some time from the flowcharts. This seems confusing to me. I'd suggest adding function `pairwise_nonparametric()` for this purpose mainly because of discoverability and  clarity. Also pls note that the documentation to `pairwise_ttests()` just says: "Pairwise T-tests.". I'd be happy to prepare PR if that helps.

**Comment by raphaelvallat** [comment]
Hi @michalkahle,

Thanks for opening the issue. I am more in favor of improving the current documentation rather than creating a whole new function. The reason for that is that the `pairwise_ttests` function is one of the longest / more complicated function in Pingouin, and I think it would be messy to duplicate 99% of it just to eventually change one line of code related to which lower-level test we're using.

We might also think about a potential function renaming, e.g. pairwise_tests.

Thanks,
Raphael

**Comment by michalkahle** [comment]
I thought about creating a new function but just calling the old one with
`parametric=False`. But I like renaming it to `pairwise_tests` even better.
The `pairwise_ttests` would be retained but just give a deprecation warning
and call `pairwise_tests`. Documentation would be updated to reflect the
various tests that could be performed in pairwise fashion. What do you
think?

**Comment by michalkahle** [comment]
I thought about creating a new function but just calling the old one with
`parametric=False`. But I like renaming it to `pairwise_tests` even better.
The `pairwise_ttests` would be retained but just give a deprecation warning
and call `pairwise_tests`. Documentation would be updated to reflect the
various tests that could be performed in pairwise fashion. What do you
think?

**Comment by raphaelvallat** [comment]
That sounds great!

**Comment by michalkahle** [comment]
Ok, working on the PR.
