### ISSUE TITLE
Varying anova outputs

### ISSUE THREAD

**Issue by bgunasekera** [raphaelvallat/pingouin#224]
Hi,

When I run the following code for an anova:

aov2 = pg.anova(dv='RT', between=['drug', 'Salient'], ss_type=3, data=plb_cbd_RT)
pg.print_table(aov2)

I get a certain output 

When I run a different pingouin anova model first, such as:
aov1 = pg.rm_anova(dv='RT',
                  within=['drug', 'Salient'],
                  subject='id_upd', data=plb_cbd_RT)

and then immediately after run the first model (aov2) again I get a different output for aov2. Although P values are similar, degrees of freedom, F statistic and other values vary massively. 

Interestingly, I re-ran the anova on SPSS as a reference and I got the exact same  output as the second aov2  model (running aov1 first and then aov2 immediately after)

What could be the reason for this? 

Please see outputs of model and code used attached

Best wishes,
Brandon

![code](https://user-images.githubusercontent.com/63005267/150350774-21127bd3-cd1a-4e5d-adf3-ef53cc015f87.jpg)
![spss](https://user-images.githubusercontent.com/63005267/150350779-95c8e415-a306-4c19-8940-02dce0f221ed.jpg)
![run2](https://user-images.githubusercontent.com/63005267/150350781-16356316-8d74-4292-9633-a508b069da42.jpg)
![run1](https://user-images.githubusercontent.com/63005267/150350783-1ee6df26-339a-4a2f-9678-06156ea1693c.jpg)

**Comment by raphaelvallat** [comment]
Hi @bjgunasekera,

Thanks for opening the issue. Are you using the latest version of Pingouin? My worry is that there could be an in-place modification of the data during the first call to the ANOVA. Could you check after each anova that `plb_cbd_RT` has not changed? For example you can make a copy with `plb_cbd_RT_backup = plb_cbd_RT.copy()` and then compare with [pandas.DataFrame.equals](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.equals.html).

Also, as good practice, when you create `df_rt` from `df` and then `plb_cbd_RT` from `df_rt`, I would always recommend that you use copy, otherwise any modifications that you make to one dataframe might end up being applied to the original dataframe (`df` or `df_rt`).

Lastly, are there any missing values in `plb_cbd_RT`?

Thanks,
Raphael

**Comment by bgunasekera** [comment]
Hi @raphaelvallat 

Many thanks for getting back. 

I updated my version to `0.5.0`. This raised `AssertionError: Factor must have at least two levels` for the `aov1 `model. However, that is okay. The purpose of my query isn't to have the `aov1 `model working, rather, to understand why the outputs of the two way anova model (`aov2`) are different. 

Despite the error, the outputs of the two way (`aov2`) remained different.

I used `plb_cbd_RT_backup = plb_cbd_RT.copy()` and then compared with pandas.DataFrame.equals as you suggested. After inspection, after running the `aov1` model the `drug` variable changed from a category to an object. My independent & dependent variables `Salient `and `RT `remained as integers and floats respectively. 

I investigated further by removing the `aov1 `model and converting the independent variables to categories. This gave the original result. I then converted the independent variables to objects. This then gave the second result.

Therefore, the rm_anova and mixed_anova (which I also tested) are performing this type conversion, from category to object. Is there a reason for this? 

Best wishes,
Brandon

**Comment by raphaelvallat** [comment]
Hi @bgunasekera,

This is related to https://github.com/raphaelvallat/pingouin/issues/127. Pandas categorical are very much error prone, because sometimes you have a category with no values, but it is still included when using functions such as pandas.DataFrame.groupby, unless specifying `observed=True`.

To avoid this, some functions of Pingouin automatically converts the categorical variables to string, e.g. for `rm_anova`:

https://github.com/raphaelvallat/pingouin/blob/dcfdc82bbc7f1ba5991b80717a5ca156617443e8/pingouin/parametric.py#L511-L516

However, there are two issues here:

1) The first is that this conversion is not applied in the [pg.anova](https://github.com/raphaelvallat/pingouin/blob/dcfdc82bbc7f1ba5991b80717a5ca156617443e8/pingouin/parametric.py#L763) function. This is something that I should add asap to avoid such errors.

2) The second is that the conversion categorical --> object should not be applied in-place — i.e. modifying your original dataframe — but instead on a copy of the dataframe.

Does that make sense? I am a little confused with the example that you gave, mostly because I do not have the data. By any chance, could you perhaps create and share here a simple toy dataset to reproduce the error?

Thanks for your help on this, I appreciate it.

Raphael

**Comment by raphaelvallat** [comment]
Quick precision: the error here only concerns N-way ANOVA and not 1-way ANOVA since we do use `observed=True` for the latter:

https://github.com/raphaelvallat/pingouin/blob/dcfdc82bbc7f1ba5991b80717a5ca156617443e8/pingouin/parametric.py#L947-L953

**Comment by bgunasekera** [comment]
Hi @raphaelvallat,

Many thanks.

I had read in another thread that you prefer data being sent in csv format. I converted the data from spss to csv and interestingly noticed that the anova outputs were corrected, despite the code being near identical. 

I suspect this is because within the spss file, the independent variables were encoded as categorical variables. Therefore, `pd.read_spss` also translated this to categorical variables within the data frame. Therefore, as you previously mentioned, given the instability of pandas categorical, this gave rise to the incorrect anova output.  Given that within the csv file there was no pre-encoding of the variables as such, `pd.read_csv` simply registered the independent variables as integers. 

Nevertheless, more than happy to share the data/ code. Unfortunately .sav files (the format of spss data) are not supported on github. Am I okay to email you all the above named files? (x2 datasets in spss+csv format & x2 scripts)

Also, I was unaware that pandas categorical was unstable. Do you have a reference for this for me to learn more?

Best wishes,
Brandon

**Comment by raphaelvallat** [comment]
Hi @bgunasekera,

Thank you for the detailed explanation. I do not have SPSS so I will not be able to read the files. You could perhaps try to export your data as a Parquet file ([pd.DataFrame.to_parquet](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_parquet.html)) which I think should save the categorical dtype.

"Unstable" is a strong word — what I meant is that the fact that some categories can be hidden (no actual value in DataFrame) can easily lead to mistakes when using groupby operations (which I use a lot!). I have not access to the full article, but this [blogpost](https://towardsdatascience.com/staying-sane-while-adopting-pandas-categorical-datatypes-78dbd19dcd8a) may also be relevant.

Best,
Raphael
