### ISSUE TITLE
[Feature Request] McGraw and Wong ICC

### ISSUE THREAD

**Issue by alabamagan** [raphaelvallat/pingouin#235]
Hi I would like to check in with the possibility of implementing the ICC by McGraw and Wong (1992) on top of the existing definition by Shrout and Fleiss (1979).

To the best of my knowledge, the IBM SPSS is currently using McGraw and Wong's implementation. It would be great to have the implementation that is used by well-established SPSS (certainly not the best user experience, but most recognized academically).

McGraw and Wong proposed 4 more definitions, but essentially, the ICCs are computed in the same way the 6 ICC forms that Shrout and Fleiss proposed. There are, however, differences in p-value calculation depending on how the raters are sampled from a larger pool. 

You can find their paper available here: https://www.researchgate.net/publication/232568057_Forming_Inferences_About_Some_Intraclass_Correlation_Coefficients

**Comment by alabamagan** [comment]
Hi @raphaelvallat, 

Thanks for the reply! I did find some R packages that claim to have implemented it: `irrNA;:icc_corr` https://cran.r-project.org/web/packages/irrNA/irrNA.pdf, but i am not all that sure they have implemented it correctly because they have no "Two-way mixed effect" implementation, only "Two-way random". After a I closer look and I am now under the impression that perhaps they are equivalent, but I am not 100% sure about it.

**Comment by keelinm** [comment]
I was looking for the same thing.  In the 2015 paper "A Guideline of Selecting and Reporting Intraclass Correlation Coefficients for Reliability Research" by Koo and Li they provide an overview of ICC types and formulae (Table 3) and pingouin is missing the 4 types that are not in Shrout et al (but are in McGraw and Wong).  Since the formulae are provided and your code already calculates the variables that are needed it should not be a big addition.  If you wanted to compare to SPSS you could do it using a free trial?  I'd really like to have the extra ones!

**Comment by keelinm** [comment]
@raphaelvallat would you consider reopening this issue?
