### ISSUE TITLE
Do eta squared and partial eta squared coincide in one-way repeated measures anova?

### ISSUE THREAD

**Issue by Federico2111** [raphaelvallat/pingouin#251]
In both the pingouin anova and rm_anova library, it is specified that, in one-way anova, eta squared and partial eta squared coincide: this means that eta squared and partial eta squared coincide both in between- and within-subjects designs, i.e. both in independent and repeated measures designs. I tested the libraries on some data sets and that is indeed true: when I calculated eta squared and partial eta squared on the same data sets, I got the same value, both with the independent and repeated measures anova library.
However, I have been discussing about this with professors, who published about statistics and effect sizes, and say otherwise. Some of them claim, providing demonstrations, that eta squared and partial eta squared coincide only in one-way between-subjects (independent) anova, but NOT in one-way within-subjects (repeated measures) anova. But I have also found publications and websites saying that, in one-way anova, eta squared and partial eta squared always coincide, without specifying the type of design, and thus I suppose including both. 
What's your opinion? 

On a different but related note, I could read in the literature that there is a method to calculate the parametric confidence interval around eta squared, using the non-central F distribution. My suggestion is to add this to the anova libraries. I think it is implemented in some R library. 

Thanks

**Comment by raphaelvallat** [comment]
Hi @Federico2111,

Thanks for opening the issue. I am not a statistican so I fear that I am not the right person to answer this. Pingouin's current behavior is similar to the reference JASP software, as shown below (`n2 == np2 != ng2`)

**Pingouin**

![image](https://user-images.githubusercontent.com/25703792/158428708-f8854f26-dce6-468b-9873-62c47ccdd6cf.png)

**JASP**

![image](https://user-images.githubusercontent.com/25703792/158428580-caf3429f-e1f5-4095-99d1-bc92353a57a4.png)

My preference would therefore **not** to make any modifications to the [pingouin.rm_anova](https://pingouin-stats.org/generated/pingouin.rm_anova.html#pingouin.rm_anova) function, unless we have a very strong rationale to do so. Moreover, what would be the calculation for the new partial eta-squared?

********

Regarding the parametric confidence intervals around the eta-square, I think this is something that could be added to the [pingouin.compute_esci](https://pingouin-stats.org/generated/pingouin.compute_esci.html#pingouin.compute_esci) function. I would suggest opening a new issue specifically for this. Please include some examples from other statistical softwares as well as any relevant literature.

Thank you,
Raphael

**Comment by Federico2111** [comment]
Thanks @raphaelvallat,

I have posted my eta squared vs partial eta squared issue on these statistics blogs. I hope that some expert will reply:

https://stats.stackexchange.com/questions/567614/do-eta-squared-and-partial-eta-squared-coincide-in-one-way-repeated-measures-ano
https://www.wyzant.com/resources/answers/888370/do-eta-squared-and-partial-eta-squared-coincide-in-one-way-repeated-measure

I will open a new issue about the eta squared parametric confidence interval, providing more details.

Federico

**Comment by rbakeman** [comment]
The pingouin rm_anova writeup and program appears to contain an error.  In your reply here, you say you are not a statistician, but pingouin’s results are the same as JASP’s results.  But what if JASP is wrong?  The matter would be cleared up if the pingouin writeup included the definitions, not just for partial eta squared, but for eta squared and generalized eta squared as well.  
 
In your reply you included a table in which gave values for eta squared, partial eta squared, and generalized eta squared for a one-way repeated measures analysis.  This table showed that eta squared and partial eta squared had the same value.  But this is impossible using standard definitions.  For a one-way repeated measures analysis eta squared and generalized eta squared will have the same value, which will be less than the value for partial eta squared.  This is easy to demonstrate.

Here are the standard definitions (e.g., Olejnik & Algina, 2002):

Eta squared = SS-effect/SS-total
Partial eta squared = SS-effect/(SS-effect + SS-error)
Generalized eta squared = SS-effect/(SS-effect + SS-error + SS-subjects)
 
As these definitions make clear, for a repeated measures factor, eta squared must always be less than partial eta squared.  It can’t be the same as partial eta squared, as you have it—unless you are using some definition for eta squared other than the standard textbook one.
 
For this one-way repeated measures example:
Generalized eta squared = 19.289722/(19.289722 + 29.672778 + 6.725000) = 0.346392.
Partial eta squared = 19.289722/(19.289722 + 29.672778) = 0.393969.
Eta squared = 19.289722/(19.289722 + 29.672778 + 6.725000) = 0.346392
(because the total sum of squares is the sum of the three sums of squares).
 
Thus your statement, “The default effect size reported in Pingouin is the partial eta-squared, which is equivalent to eta-square for one-way repeated measures ANOVA.” is incorrect.
 
Because generalized eta squared is more appropriate for a repeated measure factor (Bakeman, 2005; Olejnik & Algina, 2003), your default should be ng2 and this statement should read, “The default effect size reported in Pingouin is the generalized eta-squared, which is equivalent to eta-square for one-way repeated measures ANOVA.”
 
However, if you are using some other definition for eta squared, the writeup should say so.
 
References
Bakeman, R. (2005).  Recommended effect size statistics for repeated measures designs.  Behavior Research Methods, 37(3), 379–384. [https://doi.org/10.3758/bf03192707](https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdoi.org%2F10.3758%2Fbf03192707&data=04%7C01%7Cbakeman%40gsu.edu%7Cd179efe409954fa7a27208da09b4b916%7C515ad73d8d5e4169895c9789dc742a70%7C0%7C0%7C637832969083751950%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=6UaHqzTy7nV%2BwdR4uFkK%2BWNomX07oTQFHKCmRS%2BzNXg%3D&reserved=0)
Olejnik, S., & Algina, J. (2003).  Generalized eta and omega squared statistics:  Measures of effect size for some common research designs.  Psychological Methods, 8(4), 434–447.  [https://doi.org/10.1037/1082-989X.8.4.434](https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdoi.org%2F10.1037%2F1082-989X.8.4.434&data=04%7C01%7Cbakeman%40gsu.edu%7Cd179efe409954fa7a27208da09b4b916%7C515ad73d8d5e4169895c9789dc742a70%7C0%7C0%7C637832969083751950%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=d3EnFJaNan15Ll045NaP9Ox9GQUwlYa0AVfrd5KJ7Ew%3D&reserved=0)

**Comment by raphaelvallat** [comment]
Hi @rbakeman, thank you for the detailed explanation. I will edit as you suggest, specifically:

- [ ] Use the generalized eta-square as the default effect size in `pingouin.rm_anova`
- [ ] Update the calculation of the partial eta-square
- [ ] Add the formula of all three effect sizes in the documentation of the function.

@Federico2111 I think that we should open a similar issue on the [GitHub of JASP](https://github.com/jasp-stats/jasp-issues), with reference to the current issue.

**Comment by raphaelvallat** [comment]
Of note, the [JAMOVI software](https://www.jamovi.org/) does return the correct values:

![image](https://user-images.githubusercontent.com/25703792/159131190-9030be85-f9f4-4690-9da3-474d07f4ba41.png)

**Comment by raphaelvallat** [comment]
See pull request in https://github.com/raphaelvallat/pingouin/pull/254
