### ISSUE TITLE
shift_plt ci argument gets ignored

### ISSUE THREAD

**Issue by isaacto** [raphaelvallat/pingouin#259]
Nowhere in the code uses the "ci" value passed.  The most obvious usage should be the alpha argument of _bca, where the (1-ci) value is supposed to be passed.  In fact, the result of the _bca call overwrites the ci variable, which needs to be changed before fixing the problem.

By the way, should _bca be part of the public API?

**Comment by raphaelvallat** [comment]
Hi @isaacto,

Thanks for spotting this. Indeed, the `ci` parameter should be passed to the [_bca](https://github.com/raphaelvallat/pingouin/blob/a3e2ba6a9fc36ad34c73399b26c40b4642742b42/pingouin/regression.py#L940) function (`alpha = 1 - ci`). This will be fixed in a future release.

For bootstrapped confidence intervals, please see the new [scipy.stats.bootstrap](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.bootstrap.html) module. I think in the long term I'd like to rely exclusively on the above SciPy function for bootstrap estimation, and therefore I would prefer not to add _bca to the public API.

Thank you,
Raphael

**Comment by isaacto** [comment]
Indeed.  At present the _bca is "bc" without the "a".  On the other hand, I think scipy.stats.bootstrap missed some information: it tells you a bias corrected confidence interval, but doesn't tell you an unbiased point estimate.
