### ISSUE TITLE
Hotellings T2 test yields -df2 and NaN p value 

### ISSUE THREAD

**Issue by ejc043** [raphaelvallat/pingouin#264]
Thank you for the wonderful package! 
I am wondering if you could help guide me through this issue. 
I currently have two dataframes with equal columns(n= 2663) and rows (n=10) and am trying to conduct hotellings T2 test between the two data frames. 
However, I am yielding NaN for pval? I'm suspecting the -df2 is derived from the large amount of features-- could this be contributing to the NaN pval? 
I've attached down below 1. my inputs 
2. Hotellings output 

Thank you for your help! 
<img width="1097" alt="Screen Shot 2022-04-28 at 8 00 09 AM" src="https://user-images.githubusercontent.com/81693735/165782615-ea6e0cd6-05ac-4448-a3ae-c8bc5326186c.png">
<img width="713" alt="Screen Shot 2022-04-28 at 8 00 42 AM" src="https://user-images.githubusercontent.com/81693735/165782719-bd99e81a-3d07-4af6-9a89-f868f893ffee.png">

**Comment by raphaelvallat** [comment]
Hi @ejc043,

Indeed, the degrees of freedom are calculated as:
 https://github.com/raphaelvallat/pingouin/blob/8825a215f50a21fdaa53aa63fc25a1af44aee7bc/pingouin/multivariate.py#L247-L251

where `k` is the number of columns and `n` the sample size (`n = nx + ny - 1` for a two-sample independent test). Since `n` is much lower than `k` you end up with a negative degree of freedom and thus the p-value cannot be calculated.

I don't use this test very often, but this is not the right approach for your data. As a rule of thumb in statistics (and machine-learning), the number of samples (rows) should always be higher than the number of predictors (columns).

Thanks,
Raphael

**Comment by raphaelvallat** [comment]
Closing this issue. Feel free to re-open.
