### ISSUE TITLE
power_anova eta parameter is actually eta-squared

### ISSUE THREAD

**Issue by Riley16** [raphaelvallat/pingouin#268]
https://github.com/raphaelvallat/pingouin/blob/8825a215f50a21fdaa53aa63fc25a1af44aee7bc/pingouin/power.py#L373

The eta parameter in power_anova (and potentially functions which I haven't checked) is actually eta-squared, but the documentation doesn't make this clear enough:
eta : float
    ANOVA effect size (eta-square = 𝜂2)

The documentation as is could be taken to imply that the parameter entered by the user is eta, while the actual effect size eta-squared is the square of the user-entered parameter eta. I'd suggest making the docstring more explicit (saying something like "Actually equal to eta-squared") or renaming the parameter to eta2 or eta_squared.

**Comment by raphaelvallat** [comment]
Hi @Riley16,

(This is indirectly related to https://github.com/raphaelvallat/pingouin/pull/254)

Thanks for catching this. I think that renaming the parameter to `eta_squared` is probably the best option to avoid any confusion! Please feel free to submit a PR. Otherwise I'll just fix this in the next release of Pingouin.

Thanks,
Raphael
