### ISSUE TITLE
pg.qqplot() out of bounds

### ISSUE THREAD

**Issue by FlorinAndrei** [raphaelvallat/pingouin#285]
Data set:

[HealthExam.csv](https://github.com/raphaelvallat/pingouin/files/8944899/HealthExam.csv)

Code:

```
import numpy as np
import pandas as pd
import statsmodels.api as sm
import pingouin as pg
import seaborn as sns
import matplotlib.pyplot as plt

sns.set_theme()

he = pd.read_csv('HealthExam.csv')
fs = he['Cholesterol'].loc[he['Sex'] == "F"]

sm.qqplot(fs, line='s');
```

![sm-qq](https://user-images.githubusercontent.com/901867/174695345-f5cbfbb9-61f3-4322-b304-7a3ca6a15ac2.png)

```
pg.qqplot(fs);
```

![pg-qq](https://user-images.githubusercontent.com/901867/174695400-cf2ef2ff-5942-4363-bb8b-bce60ce4c069.png)

The output from Statsmodels QQ matches what I get from R. The output from PG extends too far to the right.

**Comment by raphaelvallat** [comment]
Pingouin forces the x-axis and y-axis to have the same units and the same limits. In your example, because there is an outlier point (y=3.5, x=2), it forces the x-axis to extend up to >3.5. Furthermore, Pingouin adds the diagonal line for easy comparison against a normal distribution

https://github.com/raphaelvallat/pingouin/blob/b1c334d93f8f7f8b13c39199c08a7d8b619afd95/pingouin/plotting.py#L381-L387

**Comment by remrama** [comment]
> I see your point, but after seeing the second image everyone goes "you need to trim the right-hand edge".

@FlorinAndrei I think you could just "trim the right-hand edge" yourself after making the plot with pingouin.

```python
ax = pg.qqplot(fs)
ax.set_xbound(upper=2.5)
```

If you are concerned with the units being rescaled on the x-axis after this, you could resize your figure to accommodate that, with something like `fig.set_figwidth` (after retrieving the figure with `fig = plt.gcf()`). Alternatively, you could mess with [setting the aspect](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.set_aspect.html) before you trim.
