### ISSUE TITLE
Reporting Extra GG Corrected Values in rm_anova

### ISSUE THREAD

**Issue by Esmerald1no** [raphaelvallat/pingouin#307]
I believe it would be a great addition to the package!
Generally, when reporting GG corrected p-values, the corrected F value and ddofs are also reported.
It is also a relatively easy addition.
(...) 
`if correction:`
 (...)  
 `corr_fval = f(corr_ddof1, corr_ddof2).ppf(1-p_corr)`

then during the formation of dataframe:
if not detailed:
(....)
`aov["F"] = corr_fval ` 
`aov["DF"] = [corr_ddof1,corr_ddof2]` 
else:
(...)
`aov["DF"] = [corr_ddof1,corr_ddof2]`
`aov["F"] = [corr_fval,np.nan]`
(...)

**Comment by raphaelvallat** [comment]
Thanks @Esmerald1no for opening the issue.

I don't think we should _replace_ the F-value and DF, because we are still reporting the uncorrected p-value. If anything, we should add the `F_corr` and `DF_corr` to the dataframe, but I am worried that it will overburden the output, which is already quite extensive.

Alternatively, we could switch to a class implementation `class RepeatedMeasuresANOVA` where there would be methods to report the corrected and non-corrected values. I've been wanting to rewrite some of these functions using https://github.com/matthewwardrop/formulaic as the backend, but this will take a significant amount of time which I don't have now.

Curious to hear your (and others) thoughts
