### ISSUE TITLE
non consistent post-hoc output

### ISSUE THREAD

**Issue by JBinkowski** [raphaelvallat/pingouin#309]
Hi, 
Many thanks for Your job, **pinguin** makes real difference in python environment!
I observed that output data frames headings from `pairwise_gameshowell`, `pairwise_tests` and `pairwise_tukey` functions are not consistent. And to some extend is understandable, but discrepancies such as: 

  - different names of columns containing p-values
  - lack of **mean(A)** and **mean(B)** in `pairwise_tests` output
  - lack of **diff** in `pairwise_tests` output
  - effect size value differ between `pairwise_gameshowell` and `pairwise_tukey`
 
makes automation more difficult, and my question is -> is it possible to standardize output from these functions?

**Comment by raphaelvallat** [comment]
Hi @JBinkowski,

Thanks for opening the issue! 

> different names of columns containing p-values

Indeed. I have been wanting to homogenize all the output variable names (including p-values), as also discussed in https://github.com/raphaelvallat/pingouin/issues/208.

> lack of mean(A) and mean(B) in pairwise_tests output

You can get these with `pg.pairwise_tests(..., return_desc=True)`

> lack of diff in pairwise_tests output

Since the `diff` can be calculated with `mean(A)` and `mean(B)`, I almost want to remove it entirely

> effect size value differ between pairwise_gameshowell and pairwise_tukey

The effect size should be the Hedges g in both cases. Is it not what you get?

**Comment by JBinkowski** [comment]
@raphaelvallat, many thanks for quick response.
1. indeed `return_desc=True` solves the problem;
2. with regard to the `effect size` issue, the results differ between implementations, please see below example:

```
from IPython.display import display
import pingouin as pg
import pandas as pd

print(pg.__version__)
df = pg.read_dataset('penguins')

def prepare(output_frame, name):  # It makes output easier to compare
    output_frame["Vs"] = output_frame.A + "_" + output_frame.B 
    output_frame.set_index("Vs", inplace=True)
    return output_frame[["hedges"]].rename({"hedges": f"hedges_from_{name}"}, axis=1)

# pairwise_tukey
result_1 = df.pairwise_tukey(dv="body_mass_g", between="species", effsize="hedges")
result_1 = prepare(result_1, "pairwise_tukey")

# pairwise_tests
result_2 = df.pairwise_tests(dv="body_mass_g", between="species", parametric=False, effsize="hedges")
result_2 = prepare(result_2, "pairwise_tests")

# pairwise_gameshowell
result_3 = pg.pairwise_gameshowell(data=df, dv="body_mass_g", between="species", effsize="hedges")
result_3 = prepare(result_3, "pairwise_gameshowell")


display(result_1.round(3), result_2.round(3), result_3.round(3))
```
and the output is:

![image](https://user-images.githubusercontent.com/27915777/199233572-f0e6e663-5256-4903-9ce9-3fb786f18a4c.png)

**Comment by raphaelvallat** [comment]
Ah, I see. So the issue here is that the Hedge values do not perfectly match between the different `pairwise_` functions, right? The output format in itself is correct. I think this behavior is definitely expected since the numerator / denominator used to calculate the effect sizes are different between implementations. For example:

https://github.com/raphaelvallat/pingouin/blob/bc795239cbf5c2f2162fc40073de465846e004a7/pingouin/pairwise.py#L889-L905

https://github.com/raphaelvallat/pingouin/blob/bc795239cbf5c2f2162fc40073de465846e004a7/pingouin/pairwise.py#L1045-L1064

**Comment by JBinkowski** [comment]
Yes, exactly that is my point. 
How this behavior may be expected if effect size (expressed as Hedges' g or any other metric) should be fixed for specific dataset, and independent to test type?
For me it seems to be a bug, or am i wrong?

**Comment by raphaelvallat** [comment]
Ah, I see your point now. So essentially you are proposing that the effect size of `pairwise_tukey` and `pairwise_gameshowell` should be calculated _a la_ `pairwise_tests`, i.e. not based on the test statistics (T and ddf) but based on the actual `x` and `y` arrays.

https://github.com/raphaelvallat/pingouin/blob/bc795239cbf5c2f2162fc40073de465846e004a7/pingouin/pairwise.py#L414

I think that makes sense. Would you be able to create a PR for it?

**Comment by JBinkowski** [comment]
Sure, i will open PR for this.

**Comment by raphaelvallat** [comment]
Done in https://github.com/raphaelvallat/pingouin/pull/328
