### ISSUE TITLE
pandas > 1.5 reason?

### ISSUE THREAD

**Issue by info-rchitect** [raphaelvallat/pingouin#416]
Hi,

Was curious if there was a specific reason to fix pandas > 1.5?  The main reason being is many commercial platforms, for example Dataiku, are very slow to upgrade their infrastructure for pandas.  Could > 1.3 work?

thx

**Comment by raphaelvallat** [comment]
Hey,

Pandas 1.5 introduced the `numeric_only` parameter in many functions 

<img width="743" alt="image" src="https://github.com/raphaelvallat/pingouin/assets/25703792/e61e2b60-d3d6-4a53-9fb9-9b9821db0eed">

Pandas 2+ changed the default value of `numeric_only=False` for most functions, which led to many user-reported errors. To avoid this, we added `numeric_only=True` to all the relevant functions, hence the dependency for pandas 1.5.

I'm not in favour of removing it because all these errors would then resurface in individual users.

Thanks
Raphael

**Comment by info-rchitect** [comment]
@raphaelvallat Thanks for taking the time to explain this.  We use Dataiku as a primary analytics tool and it is currently limited to `pandas` 1.35 for Dataiku versions < 12.5.1.  Once we convert to that we can use `pandas` 1.5.
