### ISSUE TITLE
pairwise_tukey: the 'tail' parameter does not seem to affect the p-values test results.

### ISSUE THREAD

**Issue by juanramonua** [raphaelvallat/pingouin#76]
Using the basic example:

```
from pingouin import pairwise_tukey, read_dataset
df = read_dataset('anova')
pt = pairwise_tukey(data=df, dv='Pain threshold', between='Hair color')
```

it obtains the same results as:

```
pt = pairwise_tukey(data=df, dv='Pain threshold', between='Hair color', tail='one-side')
```

I tested with 'less' and 'greater' but the results do not change.

Regards,

**Comment by raphaelvallat** [comment]
Hi @juanramonua!

It's because you forgot a "d" at the end of `"one-sided"`. The following code should give you the one-sided p-values, which are essentially the two-sided p-values divided by two. Note that `'less'` and `'greater'` do not work for this function (instead, the two-sided p-values are returned).

```
from pingouin import pairwise_tukey, read_dataset
df = read_dataset('anova')
pt = pairwise_tukey(data=df, dv='Pain threshold', between='Hair color', tail='one-sided')
```

I will make sure that an error is returned `if tail not in ['one-sided', 'two-sided']` in future releases. Thanks for pointing that out,

Raphael

**Comment by raphaelvallat** [comment]
Added assertion check for tail in c51308475c3c8e87eaed42e227669bcdd6028ed6.

Will be included in the next stable release of Pingouin (v0.3.2).
