### ISSUE TITLE
matplotlib defaults

### ISSUE THREAD

**Issue by sbwiecko** [raphaelvallat/pingouin#85]
not really an issue, but I think that pingouin should not change the matplotlib default setting. Once pingouin is loaded I need to specifiy `matplotlib.style.use('default')` in my script otherwise the figures do not look like I want

**Comment by raphaelvallat** [comment]
Hi @sbwiecko !

Pingouin indeed sets the default Seaborn style upon loading:

https://github.com/raphaelvallat/pingouin/blob/c26510c3ae40af0491ada55f9384b35f09d5366c/pingouin/plotting.py#L15

I usually prefer the default seaborn style, but I'm not against reverting back to Matplotlib default.

I'm leaving this issue open for a bit so that other people can chime in and vote.

Thanks!

**Comment by indie2020** [comment]
i'd prefer seaborn style over matplotlib style.

**Comment by mmagnuski** [comment]
I agree with @sbwiecko, I wouldn't expect a statistics library to change how all my matplotlib plots look like. An alternative could be for the style to be set with `with sns.axes_style(...):` in the plotting functions, but then changing the style of pingouin plots would be difficult. So, overall, I think it would be best if the style choice was left to the user.

**Comment by sappelhoff** [comment]
I have been surprised by this behavior as well. I would vote for pingouin *not* setting the plotting defaults.

**Comment by raphaelvallat** [comment]
Thank you all for your votes. I will disable this behavior in the next release.

**Comment by raphaelvallat** [comment]
Closing this issue for now, but please feel free to reopen.
