### ISSUE TITLE
Allow sample weights in linear regression

### ISSUE THREAD

**Issue by hammer** [raphaelvallat/pingouin#95]
`sklearn` has had this functionality since their [0.17 release](https://scikit-learn.org/stable/whats_new/v0.17.html).

**Comment by raphaelvallat** [comment]
Hi @hammer,

Thanks for your suggestion. I think the issue here is to make sure that the calculation of the SE and p-values is correct when using sample weights, which will likely require some changes in the code. I'll have to read more about that and run some tests against JASP and R. For now, I'd suggest using https://www.statsmodels.org/devel/examples/notebooks/generated/wls.html

**Comment by hammer** [comment]
Thanks @raphaelvallat, we are indeed using `statsmodels` for now, but I like your library and would love to be able to use it for our use case.

**Comment by raphaelvallat** [comment]
Hi @hammer,

I just pushed a first working version of weighted linear regression to the develop branch (1aa6a4584ac553e705f4b267e2a6308504701983). Users can now pass sample weights with:

```
pg.linear_regression(X, y, weights=w)
```

where `w` is a 1D array of non-negative real numbers with the same size as `y`.

I have updated the doc and added tests against statsmodels and R. This new feature will be included in the next stable release of Pingouin, most likely around early June.

Cheers,
Raphael
